name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build with dotnet
      run: msbuild /t:Build /p:Configuration=Release
